spring.application.name=recipe-planner

spring.datasource.url=jdbc:h2:mem:mealplanner
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=local
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/meal-planner
spring.main.lazy-initialization=true

springdoc.api-docs.enabled=true

meal-planner.h2.port: 8090
